baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'seven obelisks'
theme = "so1-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[author]
  name = "James"

[Params]
    subtitle = "Digital and analog curios - for your delight or disgust."
    description = " "
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]
  